### ISSUE TITLE
Pseudocode Compiler

### ISSUE THREAD

**Issue by emergenitro** [Sachin-dot-py/r-IGCSEBot#105]
### Summary

Implementing a feature for a pseudocode compiler

### The Problem

Many people ask "is this correct" in the ig-computer-science channel, or ask how to do something in pseudocode.

### The Ideal Solution

This is why I suggest we implement a direct pseudocode compiler into the r/IGCSE bot, similar to how texit parses mathematical expressions, we could just check what someone types, for example, starting or ending with two single quotes (') or something similar. Although my code is still in development, this shouldn't be a pain to implement as you could just send a post request like so:
```py
import requests
response = requests.post("https://fourth-fresh-boater.glitch.me/apiv1/", code={"code" : "OUTPUT 10*10 \n OUTPUT 100"})
print(response.json()) # This can then be displayed onto an embed
````

if the user's message was:
''OUTPUT 10*10''
''OUTPUT 100''

### The Current Solution

I have a website which you can post your requests to and then it'll provide back the output. As mentioned previously, it's a work-in-progress, however, most of the basic functions have been completed i.e. the loops, conditionals, and outputs.

### Additional Context

I'd love to take this up, so, if possible, can you assign this to me?

P.S. I'm itsme#2482 on Discord, and I was just wondering if I could join the Discord Bot Team.

**Comment by Sachin-dot-py** [comment]
Sure! This would be great if you could integrate it as a bot command, perhaps using Modals, and send a Pull Request.
