### ISSUE TITLE
Adding Logging features to the bot

### ISSUE THREAD

**Issue by kr1zz7007** [Sachin-dot-py/r-IGCSEBot#108]
### Summary

Basically replicates Logger Bot

### The Problem

The logger bot doesn't allow enough customisability as of know, such as image logging. It is possible to fine tune any features or add something new if its built into the bot itself

### The Ideal Solution

It basically creates an event listener for every type of action which needs to be logged, and sends it in a log channel

### Additional Context

PS: Maybe you can assign this issue to me and @emergenitro ?

**Comment by Sachin-dot-py** [comment]
Closed to be included in `v3.0` of r/IGCSE bot.
