### ISSUE TITLE
Add a 'user is not banned' message

### ISSUE THREAD

**Issue by Sachin-dot-py** [Sachin-dot-py/r-IGCSEBot#19]
Send a 'user is not banned' message if a moderator attempts to unban a person who is not banned in the first place.

**Comment by YousefRofa** [comment]
I have this in my code 
add a function with the name (check_ban) I suggest adding it with the isModerator and isHelper functions that you have 
`async def is_banned(user, interaction: discord.Interaction):
    try:
        await interaction.guild.fetch_ban(user)
        return True
    except discord.NotFound:
        return False`
        
 then call the function on banning/muting/timeing out/kicking/unmuting/untiming out members like this:
 
 `        if await is_banned(user, interaction):
            await interaction.send("User is banned from the server", ephemeral=True)
            return`
            
This worked perfectly for me
